/analysis/setOutputROOTTreeName nEXOevents

/control/verbose 1
/nEXO/det/checkOverlap true

# Use Baseline 2017
/control/execute ./yamls/Baseline2017.mac

/run/initialize

/generator/setGenerator gps 

/gps/particle ion 
/gps/energy 0 keV 
/gps/ion 83 214
/grdm/nucleusLimits 214 214 83 83

/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 0 0 -403 mm
/gps/pos/radius 642.5 mm
/gps/pos/halfz 652.88 mm
/gps/pos/confine /nEXO/TPCVessel
